language: groovy

sudo: false

jdk:
  - openjdk8

install: true

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - chmod +x gradlew

env:
  - TERM=dumb

script:
  - ./gradlew getGit -Pcomponent=example
  - ./gradlew load
  - ./gradlew runtime:component:example:test --info

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
